/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package chess;

import java.util.Scanner;

public class ChessGame {
    private static final String START_GAME = "start";
    private static final String END_GAME = "end";
    private static final Scanner scanner = new Scanner(System.in);

    public static void main(String[] args) {
        Board board = new Board();
        String input = "";

        while (!input.equals(END_GAME)) {
            input = getLine();
            if (input.equals(START_GAME))
                board.start();
            if (Validator.isValidPosition(input)) {

            }
        }
    }

    private static String getLine() {
        System.out.print("명령을 입력하세요. (end : 종료) : ");
        return scanner.nextLine();
    }
}
